language: python

python:
      - 3.5

services:
      - docker

addons:
  apt:
      packages:
        - pyqt5-dev-tools


script:
    -  docker-compose -f docker/docker-compose.travis.yml run qgis bash docker/run_tests.sh
