language: python

python:
      - 3.5

services:
      - docker

addons:
  apt:
      packages:
        - pyqt5-dev-tools

env:
    - QGIS_TEST_VERSION="latest"

script:
    -  docker-compose -f docker/docker-compose.travis.yml run qgis bash /usr/src/docker/run_tests.sh
